---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: open-app
  name: open-app
  namespace: suriyadk7-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: open-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: open-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/suriyadk7-dev/openshift-git:latest
        name: hello-world
        resources: {}
		ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: open-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
